%   Presentation 1 Code

%   This code generates predicted fMRI images from word vectors using 
%   machine learning. The word vectors are taken from the existing lexvec
%   model and represent the meaning of a word in 300 dimensions 
%   generated by analyzing large bodies of online text.
%   Lexvec model: https://github.com/alexandres/lexvec

%   This code trains on 58 words, using the 300 dimensions as 
%   characteristics which can be used to predict the voxel of one
%   fMRI scan collected by Jeffrey et al. 2008.

%   After generating the predicted activation of the voxels, these numbers
%   are mapped to NMI space using the functions supplied by Jeffrey et al.
%   2008.

%   AUTHOR: DAVINA KAM DATE: JANUARY 30, 2020
%   Patient data and code for mapping to NMI space available at:
%   https://www.cs.cmu.edu/afs/cs/project/theo-73/www/science2008/data.html

%% Load relevant data
load('patient1_data.mat')
%   words: cell array of the 60 words shown to patients in the Jeffrey et. 
%   al 2008 study
%   data: rows = words, columns = activation for each voxel.
%   Each value of data is the activation of a particular voxel when patient 1
%   sees that word on the screen. 
%   model_x_values: rows = words, columns = value for one of the 300
%   dimensions determined by lexvec
%   Each value o
%   Example: row 1 in cell array 'words' has the value of 'airplane'. 
%   Row 1 column 1 in double matrix 'data' corresponds to the activation of
%   voxel 1 when patient 1 saw the word 'airplane'.
%   Row 1 column 1 in double matrix 'model_x_values' corresponds to the 
%   value of dimension 1 for the word 'airplane' as determined by the
%   lexvec model.

%% Training and Testing
num_voxels = length(data(1,:));
pred_airplane = ones(num_voxels, 1);
pred_ant = ones(num_voxels,1);
for voxel_index = 1:num_voxels
    %   Model trains on 58 words to predict the fMRI images for the first 
    %   two words, airplane and ant
    weights = ridge(data(3:60,voxel_index), model_x_values(3:60,:), 100);
    %   Generate predicted activation values for each voxel for the
    %   words hammer and dog
    pred_airplane(voxel_index) = model_x_values(1,:) * weights;
    pred_ant(voxel_index) = model_x_values(2,:) * weights;
end

%% Mapping to MNI space

%   Use functions written by Jeffrey et al. 2008 to generate predicted fMRI
%   image using the voxel activation values previously calculated.



