%   Presentation 1 Code

%   REQUIRED SETUP: Install image processing toolbox. 

%   This code generates machine learning predicted 2D-fMRI images based on  
%   word vectors. The word vectors are taken from the existing lexvec
%   model and represent the meaning of a word in 300 dimensions 
%   generated by analyzing large bodies of online text.

%   This code trains on 58 words, using the 300 dimensions as 
%   characteristics which can be used to predict the voxel of one
%   fMRI scan collected by Jeffrey et al. 2008.

%   After generating the predicted activation of the voxels, these numbers
%   are mapped to NMI space and plotted using the functions written by
%   Jeremy Manning.

%   AUTHOR: DAVINA KAM DATE: JANUARY 30, 2020

%   References:

%   Lexvec model: https://github.com/alexandres/lexvec
%   Patient data available at:
%   https://www.cs.cmu.edu/afs/cs/project/theo-73/www/science2008/data.html
%   Code for plotting brain images:
%   Jeremy Manning (2020). 2d and 3d brain plots 
%   (https://www.mathworks.com/matlabcentral/fileexchange/36139-2d-and-
%   3d-brain-plots), MATLAB Central File Exchange. Retrieved February 4, 2020.
%   Code for colors:
%   Jonathan C. Lansey (2020). Beautiful and distinguishable line colors + 
%   colormap (https://www.mathworks.com/matlabcentral/fileexchange/
%   42673-beautiful-and-distinguishable-line-colors-colormap), 
%   MATLAB Central File Exchange. Retrieved February 4, 2020.

%% Load relevant data
load('patient1_data.mat')
load('data-science-P1.mat', 'meta')
%   words: cell array of the 60 words shown to patients in the Jeffrey et. 
%   al 2008 study

%   matrix_data: rows = words, columns = activation for each voxel.
%   Each value of data is the activation of a particular voxel when patient 1
%   sees that word on the screen. 

%   model_x_values: rows = words, columns = value for one of the 300
%   dimensions determined by lexvec
%   Each value of model_x_values represents the value of a certain
%   dimension for a certain word

%   Example: Row 1 in cell array 'words' has the value of 'airplane'. 
%   Row 1 column 1 in double matrix 'data' corresponds to the activation of
%   voxel 1 when patient 1 saw the word 'airplane'.
%   Row 1 column 1 in double matrix 'model_x_values' corresponds to the 
%   value of dimension 1 for the word 'airplane' as determined by the
%   lexvec model.

%% Training and Testing
num_voxels = length(matrix_data(1,:));
pred_airplane = ones(num_voxels, 1);
pred_ant = ones(num_voxels,1);
for voxel_index = 1:num_voxels
    %   Model trains on 58 words to predict the fMRI images for the first 
    %   two words, airplane and ant
    weights = ridge(matrix_data(3:60,voxel_index), model_x_values(3:60,:), 100);
    %   Generate predicted activation values for each voxel for the
    %   words hammer and dog
    pred_airplane(voxel_index) = model_x_values(1,:) * weights;
    pred_ant(voxel_index) = model_x_values(2,:) * weights;
end

%% Mapping to MNI spacce

%   Use functions written by Jeremy Manning to generate predicted fMRI
%   image using the voxel activation values previously calculated.
figure(1)
plot_brain2d_alt(pred_airplane',meta);
figure(2)
plot_brain2d_alt(pred_ant',meta);


