%   Presentation 1 Code

%   This code generates predicted fMRI images from word vectors using 
%   machine learning. The word vectors are taken from the existing lexvec
%   model and represent the meaning of a word in 300 dimensions 
%   generated by analyzing large bodies of online text.
%   Lexvec model: https://github.com/alexandres/lexvec

%   This code trains on 58 words, using the 300 dimensions as 
%   characteristics which can be used to predict the voxel of one
%   fMRI scan collected by Jeffrey et al. 2008.

%   After generating the predicted activation of the voxels, these numbers
%   are mapped to NMI space using the functions supplied by Jeffrey et al.
%   2008.

%   AUTHOR: DAVINA KAM DATE: JANUARY 30, 2020
%   Patient data and code for mapping to NMI space available at:
%   https://www.cs.cmu.edu/afs/cs/project/theo-73/www/science2008/data.html